Solo-Trade-Journal/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash, check_password_hash
import base64
import requests
from models import Users, TradingAccounts, CopyTrading, db
from datetime import datetime, timedelta, timezone
from dateutil import parser
import math
import pprint
import json
from dotenv import load_dotenv
import os

#   Creating a blueprint ( area for all the routes )
views = Blueprint("views", __name__)

# TradeSync API
base_url = "https://api.tradesync.io/"

load_dotenv('.env')
apikey: str = os.getenv('API_KEY')
secretkey: str = os.getenv('SECRET_KEY')

credentials = f"{apikey}:{secretkey}"

encoded = base64.b64encode(credentials.encode()).decode()

header = {
    "Authorization": f"Basic {encoded}",
    "Content-Type": 'application/json'  # Fixed typo here
}

@views.route("/")
def index():
    return render_template("index.html")


@views.route("/signup", methods=["POST", "GET"])
def signup():
    minCharacters = 8
    error = None
    page_title = "Signup"

    if request.method == "POST":
        name = request.form.get("name")
        email = request.form.get("email")
        password = request.form.get("password")
        password = generate_password_hash(password)
        print(name, email, password)

        if len(password) < minCharacters :
            error_message = "More characters"
            return render_template('signup.html', page_title=page_title, error_message=error_message)

        #   Add user to database
        new_user = Users(name=name, email=email, password=password)
        print(new_user)
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for("views.login"))

    return render_template("signup.html", page_title=page_title)



@views.route("/login", methods=["POST", "GET"])
def login():
    page_title = "Login"
    error = None

    # Checking if user exists
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")
        print("User Credentials: ", email, password)

        #   Check if user exists
        user = Users.query.filter_by(email=email).first()
        print("User:", user)
        if user and check_password_hash(user.password, password):
            session['user_id'] = user.id
            return redirect(url_for("views.accounts"))
        else:
            error = "Invalid email or password"
            return render_template("login.html", page_title=page_title, error=error)


    return render_template("login.html", page_title=page_title)


@views.route("/accounts", methods=["POST", "GET"])
def accounts():

    def get_brokers():
        endpoint = "brokers"
        url = base_url + endpoint
        response = requests.get(url, headers=header)
        data = response.json()
        data = data['data']

        all_brokers = []
        for broker in data:
            all_brokers.append(broker)
        return all_brokers
    def get_broker_servers():
        endpoint = "broker-servers"
        url = base_url + endpoint
        response = requests.get(url, headers=header)
        data = response.json()
        data = data['data']

        all_broker_servers = []
        for broker_server in data:
            all_broker_servers.append(broker_server)

        return all_broker_servers

    if request.method == "POST":

        trading_name = request.form.get("name")
        trading_number = request.form.get("account-login")
        trading_password = request.form.get("password")
        mt_version = request.form.get("mt-version")
        trading_broker = request.form.get("broker")
        trading_server = request.form.get("broker-server")

        """
        print("Trading Name: ", trading_name)
        print("Trading Number: ", trading_number)
        print("Trading Password: ", trading_password)
        print("MT Version: ", mt_version)
        print("Trading Broker: ", trading_broker)
        print("Trading Server: ", trading_server)
        """

        def create_account():
            endpoint = "accounts"
            url = base_url + endpoint
            data = {
                "account_name": trading_name,
                "account_number": trading_number,
                "password": trading_password,
                "mt_version": mt_version,
                "broker_id": trading_broker,
                "broker_server_id": trading_server
            }
            response = requests.post(url, headers=header, json=data)
            print("Response: ", response.json())
            return response.json()

        data = create_account()
        if data['status'] == 200:
            new_account = TradingAccounts(user_id=session['user_id'], name=trading_name,
                                          account_number=trading_number)
            db.session.add(new_account)
            db.session.commit()

            return redirect(url_for("views.accounts"))


    accounts = TradingAccounts.query.filter_by(user_id=session['user_id']).all()
    return render_template("accounts.html", all_brokers=get_brokers(),
                           all_servers=get_broker_servers(), accounts=accounts)



@views.route("/dashboard/<int:account_id>")
def dashboard(account_id):

    def get_trading_account_id(account_id):
        session['account_id'] = account_id
        account = TradingAccounts.query.filter_by(id=account_id).first()
        return account.account_number

    def get_acc_pnl(tradesync_acc_id):
        print("TradeSync Account ID: ", tradesync_acc_id)

        endpoint = "accounts"
        url = base_url + endpoint
        response = requests.get(url, headers=header)
        data = response.json()
        data = data['data']
        print("Account Data: ", data)

        for account in data:
            if account['account_number'] == tradesync_acc_id:
                return account

    def get_trades(tradesync_account_id):
        endpoint = "accounts"
        url = base_url + endpoint
        response = requests.get(url, headers=header)
        data = response.json()
        data = data['data']

        for account in data:
            if account['account_number'] == tradesync_account_id:
                ts_account = account

        ts_account_id = ts_account['id']
        session['tradesync_acc_id'] = ts_account_id

        endpoint = "trades"
        url = base_url + endpoint
        response = requests.get(url, headers=header)
        data = response.json()
        data = data['data']

        trades_list = []
        for trade in data:
            if trade['account_id'] == ts_account_id:
                trades_list.append(trade)

        return trades_list

    def get_monthly_growth(tradesync_account_id):
        endpoint = f"analyses/{tradesync_account_id}/monthlies"
        url = base_url + endpoint
        response = requests.get(url, headers=header)
        data = response.json()
        return data['data']



    tradesync_account_id = int(get_trading_account_id(account_id))
    session['tradesync_acc_number'] = tradesync_account_id

    # Top row variables
    acc_dict = get_acc_pnl(tradesync_account_id)
    weekly_profit = acc_dict['weekly_profit']
    monthly_profit = acc_dict['monthly_profit']
    balance = acc_dict['equity']

    # Chart data
    monthly_growth = get_monthly_growth(session['tradesync_acc_id'])
    json_data = json.dumps(monthly_growth)

    # Trades Table
    trades_list = get_trades(tradesync_account_id)
    session['trades_list'] = trades_list



    return render_template("dashboard.html", weekly_profit=weekly_profit, monthly_profit=monthly_profit
                           , balance=balance, trades_list=trades_list, json_data=json_data)


@views.route("/dashboard/<int:account_id>/analysis")
def analysis(account_id):

    account_id = session['account_id']
    def get_trading_account_id(account_id):
        session['account_id'] = account_id
        account = TradingAccounts.query.filter_by(id=account_id).first()
        return account.account_number

    def get_trades(tradesync_account_id):
        endpoint = "accounts"
        url = base_url + endpoint
        response = requests.get(url, headers=header)
        data = response.json()
        data = data['data']

        for account in data:
            if account['account_number'] == tradesync_account_id:
                ts_account = account

        ts_account_id = ts_account['id']
        session['tradesync_acc_id'] = ts_account_id

        endpoint = "trades"
        url = base_url + endpoint
        response = requests.get(url, headers=header)
        data = response.json()
        data = data['data']

        trades_list = []
        for trade in data:
            if trade['account_id'] == ts_account_id:
                trades_list.append(trade)

        return trades_list


    tradesync_account_id = int(get_trading_account_id(account_id))
    trades_list = get_trades(session['tradesync_acc_number'])
    print("Trades List: ", trades_list)

    return render_template("analysis.html")


@views.route("/copytrading")
def copytrading():
    return render_template("copytrading.html")

@views.route("/delete-account/<int:account_id>")
def delete_account(account_id):
    account = TradingAccounts.query.filter_by(id=account_id).first()
    db.session.delete(account)
    db.session.commit()

    account_id = session['tradesync_acc_id']

    endpoint = f"accounts/{account_id}"
    url = base_url + endpoint
    response = requests.delete(url, headers=header)
    print("Delete Response:", response.json())

    return redirect(url_for("views.accounts"))

Solo-Trade-Journal/templates/accounts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Accounts</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <!-- Import the Lightweight Charts -->
    <script src="https://unpkg.com/lightweight-charts/dist/lightweight-charts.standalone.production.js"></script>
    <style>
        body {
          font-family: "Plus Jakarta Sans", sans-serif;
          background-color: #ededed;
          color: black;
        }
    </style>
</head>
<body>
    <nav>
        <img src="https://media.discordapp.net/attachments/954082449888006184/1243325550924136498/Solo_Journal_Logo_2.png?ex=665110a7&is=664fbf27&hm=8cd6fc23332188d2f3baf2c72f81965b5c771de302307c460eb0fcd19183b36d&=&format=webp&quality=lossless&width=375&height=195" alt="Logo">
    </nav>
    <style>
        nav {
            display: flex;
            justify-content: center;
            align-items: center;
            max-height: 50px;
        }

        nav img {
            display: block;
            max-width: 15%;
        }
    </style>
    <div class="container">
        <h3>All Accounts</h3>
        <div class="table-container">
            <div class="table-item">
                <button onclick="addAccount()">Add Account</button>
            </div>
            <table>
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Option</th>
                </tr>
                </thead>
                <tbody>
                {% for account in accounts %}
                <tr>
                    <td>
                        <a href="{{ url_for('views.dashboard',account_id=account.id)}}">{{ account.name }}</a>
                    </td>
                    <td>
                        <button>
                            <a href="{{ url_for('views.delete_account', account_id=account.id)}}">Delete</a>
                        </button>
                        <style>
                            td button {
                                background-color: blue;
                                color: white;
                                padding: 5px;
                                border-radius: 5px;
                                border: none;
                            }

                            button a{
                                color: white;
                                text-decoration: none;
                            }
                        </style>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="chart-card">
            <div id="container">
            </div>
        </div>

        <div id="backgroundOverlay">
        </div>
        <style>
            #backgroundOverlay {
                position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                background-color: rgba(0, 0, 0, 0.5); /* semi-transparent black */
                z-index: 999; /* any value less than the z-index of #addAccount */
                display: none; /* initially hidden */
            }
        </style>

        <div class="" id="addAccount">
            <div class="overlay-header">
                <div class="overlay-title">
                    <h3>Add Account</h3>
                </div>
                <div class="overlay-close">
                    <button onclick="addAccount()">X</button>
                </div>
            </div>
            <div class="overlay-body">
                <form action="/accounts" method="post">
                    <div class="form-element">
                        <label for="name">Name:</label><br>
                        <input type="text" name="name" id="name" placeholder="Personal Account">
                    </div>
                    <div class="form-element">
                        <label for="account-login">Account Number:</label><br>
                        <input type="text" name="account-login" id="account-login" placeholder="109908009">
                    </div>
                    <div class="form-element">
                        <label for="password">Password</label><br>
                        <input type="text" name="password" id="password" placeholder="abcdefg">
                    </div>
                    <div class="form-element">
                        <label for="mt-version">MT-Version</label><br>
                        <input type="number" name="mt-version" id="mt-version" placeholder="5 or 4">
                    </div>
                    <div class="form-element">
                        <label for="broker">Broker</label><br>
                        <select name="broker" id="broker">
                            {% for broker in all_brokers %}
                            <option value="{{ broker.id }}">{{ broker.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-element">
                        <label for="broker-server">Broker Server</label><br>
                        <select name="broker-server" id="broker-server">
                            {% for server in all_servers %}
                            <option value="{{ server.id }}">{{ server.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit">Submit</button>
                </form>

                <div class="error">
                    {% if error %}
                    <p>{{ error_message }}</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <style>
        .container {
            padding: 10px;
        }

        .table-item {
            padding-bottom: 10px;
        }

        .table-item button {
            background-color: blue;
            color: white;
            border: none;
            border-radius: 12px;
            padding: 8px;
        }

        button {
            font-family: "Plus-Jakarta-Sans", sans-serif;
            border-radius: 10px;
        }

        .table-container {
            border: 1px solid black;
            background-color: white;
            border-radius: 20px;
            min-height: 70%;
            padding: 10px;
            padding-bottom: 10px;
        }

        table {
            text-align: center;
            width: 100%;
        }

        thead {
            text-decoration: underline;
        }



        #addAccount {
            border-radius: 20px;
            border: 1px solid black;
            background-color: white;
            margin: 10px auto;
            padding: 10px;
            width: 70%;
            max-width: 600px;
            display: none;
            z-index: 9999;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            margin: auto;
            position: fixed;
        }

        .overlay-header {
            width: 100%;
            display: flex;
            justify-content: space-between;
            align-items: center;
            text-align: center;
        }

        .overlay-body {
            justify-content: center;
            align-items: center;
        }

        .overlay-close {
            margin-right: 0;
        }

        label {
            font-size: 0.5 rem;
        }

        input {
            height: 2.2rem;
            width: 100%;
            max-width: 100%;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 5px;
            padding: 0;
        }

        /*input::value {
            font-size: 16px; /* Change the font size */
            text-align: center; /* Center the placeholder text */
        }*/

        form {
            width: 100%;
            padding: 5px;
        }

        .form-element {
            margin-bottom: 10px;
        }

        form button {
            width: 100%;
            height: 3rem;
            font-size: 1rem;
            background-color: blue;
            color: white;
        }

        select {
            width: 100%;
            max-width: 100%;
        }
    </style>

    <script>
        // Add Account function
        function addAccount() {
            var overlay = document.getElementById("addAccount");
            var backgroundOverlay = document.getElementById("backgroundOverlay");
            if (overlay.style.display === "none" ) {
                overlay.style.display = "block";
                backgroundOverlay.style.display = "block"; // show the background overlay
            } else {
                overlay.style.display = "none";
                backgroundOverlay.style.display = "none"; // hide the background overlay
            }
        }

    </script>
</body>
</html>

Solo-Trade-Journal/templates/analysis.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Analysis</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">


    <!-- Import the Lightweight Charts -->
    <script src="https://unpkg.com/lightweight-charts/dist/lightweight-charts.standalone.production.js"></script>
    <style>
        body {
          font-family: "Plus Jakarta Sans", sans-serif;
          background-color: #ededed;
          color: black;
        }
    </style>
</head>
<body>
    <nav>
        <img src="https://media.discordapp.net/attachments/954082449888006184/1243325550924136498/Solo_Journal_Logo_2.png?ex=665110a7&is=664fbf27&hm=8cd6fc23332188d2f3baf2c72f81965b5c771de302307c460eb0fcd19183b36d&=&format=webp&quality=lossless&width=375&height=195" alt="Logo">
    </nav>
    <style>
        nav {
            display: flex;
            justify-content: center;
            align-items: center;
            max-height: 50px;
        }

        nav img {
            display: block;
            max-width: 15%;
        }
    </style>
    <div class="container">
        <h3>Analysis</h3>
        <div class="card">
            <div style="overflow-x:auto;">
                <table>
                    <thead>
                        <tr>
                            <th>Tags</th>
                            <th>Day</th>
                            <th>Open Time</th>
                            <th>Symbol</th>
                            <th>Type</th>
                            <th>Lots</th>
                            <th>RR</th>
                            <th>Outcome</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for trade in trades_list %}
                        <tr>
                            <td>{{ trades_list.tags }}</td>
                            <td>{{ trades_list.day }}</td>
                            <td>{{ trades_list.open_time }}</td>
                            <td>{{ trades_list.symbol }}</td>
                            <td>{{ trades_list.type }}</td>
                            <td>{{ trades_list.lots }}</td>
                            <td>{{ trades_list.rr }}</td>
                            <td>{{ trades_list.outcome }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <style>
            .container {
                padding: 10px;
            }

            .card {
                justify-content: center;
                align-items: center;
                padding: 10px;
                border: 1px solid black;
                border-radius: 20px;
                background-color: white;
            }

            table {
                width: 100%;
                border-collapse: collapse;
            }

            th, td {
                text-align: center;
            }

            tr:nth-child(even) {
                background-color: #f2f2f2;
            }
        </style>
    </div>
</body>
</html>

Solo-Trade-Journal/templates/authbase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <style>
        body{
            background-color: #F5F5F5;
            font-family: 'Roboto', sans-serif;
        }

        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh; /* Full height of the viewport */
        }

        .card {
            border-radius: 30px;
            padding: 20px;
            background-color: white;
            justify-content: center;
            align-items: center;
        }

        .card-title {
            padding: 10px;
            text-align: center;
        }

        .card-body {
            display: flex;
            justify-content: center;
            align-items: center;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-title">
                <h2>{{ page_title }}</h2>
            </div>
            <div class="card-body">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

Solo-Trade-Journal/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap Styling -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">

    <!-- Jinja Title -->
    <title>{% block title %}{% endblock %}</title>

    <!-- Styling Area -->
    <style>
        body {
            font-family: 'Plus Jakarta Sans', sans-serif;
        }
    </style>
</head>
<body>
    <!-- Navbar Area -->
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <img src="#" alt="">
            <button onclick="menuToggle()" class="navbar-toggler"
                    type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                      <a class="nav-link" href="/login">Log-in</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="/signup">Sign-Up</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Main Container -->
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <!-- JavaScript Area -->
    <script>
        function menuToggle(){
            var overlay = document.getElementById("navbarSupportedContent");
            var computedStyle = window.getComputedStyle(overlay);
            if (computedStyle.display === "none" || computedStyle.display === ""){
                overlay.style.display = "flex";
            } else {
                overlay.style.display = "none";
            }
        }
    </script>
</body>
</html>

Solo-Trade-Journal/templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="container">
    <div class="card">
        <h2>Welcome to Solo Journal the key to your trading success</h2>
        <div class="buttons">
            <button>
                <a href="/signup">Get Started</a>
            </button>
            <button>
                <a href="/login">Log In</a>
            </button>
        </div>
    </div>
</div>
<style>

    .container {
        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;
        height: 80vh; /* Full height of the viewport */
    }

    .card {
        padding: 10px;
        border: none;
    }

    .buttons {
        display: grid;
        padding-top: 20px;
        justify-content: center;
        gap: 0.5rem;
        grid-template-columns:
            repeat(auto-fit, minmax(100px, 1fr));
    }

    .buttons button {
        border: none;
        border-radius: 5px;
        background-color: blue;
        color: white;
    }

    button a {
        text-decoration: none;
        color: white;
        box-shadow: 0 0 5px rgba(0,0,0,0.1);
    }
</style>
{% endblock %}

Solo-Trade-Journal/templates/login.html
{% extends "authbase.html" %}

{% block title %}Login{% endblock %}


{% block content %}
<div class="form-container">
    <form action="{{ url_for('views.login') }}" method="post">
        <div class="form-element">
            <div class="form-item">
                <label for="email">Email</label><br>
                <input type="text" name="email" id="email" required>
            </div>
            <div class="form-item">
                <label for="password">Password</label><br>
                <input type="password" name="password" id="password" required>
            </div>
            <div class="submit">
                <button type="submit">Login</button>
            </div>
        </div>
    </form>
    <div class="error">
        <p>{{ error }}</p>
    </div>
</div>
<style>
    .form-element {
        display: flex;
        flex-direction: column;
    }

    .form-item {
        padding-bottom: 10px;
    }

    .submit {
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .submit button {
        background-color: #2481f2;
        color: white;
        padding: 5px;
        border: none;
        border-radius: 5px;
    }

    .error {
        display: flex;
        justify-content: center;
        align-items: center;
    }
</style>
{% endblock %}

Solo-Trade-Journal/templates/signup.html
{% extends "authbase.html" %}

{% block title %}Sign-Up{% endblock %}


{% block content %}
<div class="form-container">
    <form action="{{ url_for('views.signup') }}" method="post">
        <div class="form-element">
            <div class="form-item">
                <label for="name">Name</label><br>
                <input type="text" name="name" id="name" required>
            </div>
            <div class="form-item">
                <label for="email">Email</label><br>
                <input type="text" name="email" id="email" required>
            </div>
            <div class="form-item">
                <label for="password">Password</label><br>
                <input type="password" name="password" id="password" required>
            </div>
            <div class="submit">
                <button type="submit">Sign Up</button>
            </div>
        </div>
    </form>
    <div class="error">
        <p>{{ error }}</p>
    </div>
</div>
<style>
    .form-element {
        display: flex;
        flex-direction: column;
    }

    .form-item {
        padding-bottom: 10px;
    }

    .submit {
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .submit button {
        background-color: #2481f2;
        color: white;
        padding: 5px;
        border: none;
        border-radius: 5px;
    }

    .error {
        display: flex;
        justify-content: center;
        align-items: center;
    }
</style>
{% endblock %}